comentarios:    
    resource: "@ComentariosBundle/Resources/config/routing.yml"

front:    
    resource: "@FrontBundle/Resources/config/routing.yml"

noticias:
    resource: "@NoticiasBundle/Resources/config/routing.yml"
    
CategoriasBundle:
    resource: "@CategoriasBundle/Resources/config/routing.yml"

prensa:
    resource: "@PrensaBundle/Controller/"
    type:     annotation
    prefix:   /manager/prensa/

tips:
    resource: "@TipsBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /manager/tips/

categorias:
    resource: "@TipsBundle/Controller/CategoriasController.php"
    type:     annotation
    prefix:   /manager/destacados/categorias/

keywords:
    resource: "@TipsBundle/Controller/KeywordsController.php"
    type:     annotation
    prefix:   /manager/destacados/keywords/

destcados:
    resource: "@DestcadosBundle/Controller/"
    type:     annotation
    prefix:   /manager/destacados/

admin:
    resource: '@AdminBundle/Controller/'
    type: annotation
app:
    resource: '@AppBundle/Controller/'
    type: annotation
