prensa:
    resource: "@PrensaBundle/Controller/"
    type:     annotation
    prefix:   /manager/prensa/

tips:
    resource: "@TipsBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /manager/tips/

categorias:
    resource: "@TipsBundle/Controller/CategoriasController.php"
    type:     annotation
    prefix:   /manager/categorias/

destcados:
    resource: "@DestcadosBundle/Controller/"
    type:     annotation
    prefix:   /manager/destacados/

admin:
    resource: '@AdminBundle/Controller/'
    type: annotation
app:
    resource: '@AppBundle/Controller/'
    type: annotation
