destcados:
    resource: "@DestcadosBundle/Controller/"
    type:     annotation
    prefix:   /manager/destacados/

admin:
    resource: '@AdminBundle/Controller/'
    type: annotation
app:
    resource: '@AppBundle/Controller/'
    type: annotation
