# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    access_denied_url: 
    encoders:
        AppBundle\Entity\Usuario:
                algorithm: bcrypt

        Symfony\Component\Security\Core\User\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    doubledot:
                        password: $2y$13$k.m4ZFd8yBlUokXY1CAw6.kmqeNJx98D/LTfeNSD7mb.I/7Z1euiW
                        roles: [Administrador,Super]

        administracion:
            entity:
                class: AdminBundle:Admin
                property: username

        chain_provider:
            chain:
                providers: [in_memory, administracion]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
        admin:
            pattern: (.*)
            anonymous: ~
            form_login:
                login_path:                     /manager/login
                check_path:                     /manager/login
                success_handler:                acceso
                always_use_default_target_path: true
                provider:                       chain_provider
                default_target_path:            
                target_path_parameter:          _target_path                
                use_referer:                    false
                require_previous_session:       false
                remember_me:                    true                
            remember_me:
                secret:                 "%secret%"
                name:                   doubledot
                lifetime:               86400 # in seconds
                path:                   
                domain:                 ~
                always_remember_me:     false
                remember_me_parameter:  _remember_me
            logout:
                path:               /manager/logout
                target:             /manager
                invalidate_session: true
        
    access_control:
        - { path: /manager/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /manager/renovar/pass, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /manager/*, roles: IS_AUTHENTICATED_REMEMBERED }
