services:
  my.listener:
    class: TipsBundle\Events\Listener
    arguments: ["@normalizator"]
    tags:
        - { name: doctrine.event_listener, event: prePersist }
        - { name: doctrine.event_listener, event: preUpdate }
