services:
#    newsletter.example:
#        class: NewsletterBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    NewsletterBundle\Form\NewsletterForm:
        arguments: ['@doctrine.orm.entity_manager',"@security.token_storage"]
        tags: [form.type]    